apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: sample-add-pipeline
spec:
  taskRef:
    name: kf-pipeline-run
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/swiftdiaries/kf-app-tekton
    params:
    - name: notebook-filepath
      value: /workspace/src/sample-notebook/add.ipynb
    - name: flags
      value: ""
