apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kf-pipeline-run
spec:
  inputs:
    params:
    - name: notebook-filepath
      description: "KF Pipeline notebook filepath"
      default: "./pipeline/pipeline.ipynb"
    - name: version
      description: pipeline runner version to use
      default: "v0.0.1"
    resources:
    - name: source
      type: git
      targetPath: /src
  steps:
  - name: build
    image: docker.io/ciscoai/pipeline-runner:$(inputs.params.version)
    script: |
      jupyter kernelspec list
      papermill --kernel python3 $(inputs.params.notebook-filepath) $(inputs.params.notebook-filepath)
