apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kf-pipeline-run
spec:
  inputs:
    params:
    - name: notebook-filepath
      description: "KF Pipeline notebook filepath"
      default: "./pipeline/pipeline.ipynb"
    - name: version
      description: pipeline runner version to use
      default: "latest"
    - name: flags
      description: flags to use for the papermill command
      default: ""
    resources:
    - name: source
      type: git
      targetPath: src/$(inputs.params.notebook-directory)
  steps:
  - name: build
    image: docker.io/ciscoai/pipeline-runner:$(inputs.params.version)
    workingDir: /workspace/src/$(inputs.params.notebook-directory)
    script: |
      papermill $(inputs.params.notebook-directory) $(inputs.params.flags)
